
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk


###

GET http://localhost:3000/states/16/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk

###

POST http://localhost:3000/districts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk


{
  "districtName": "Gorakhpur",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/12/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk

###

DELETE http://localhost:3000/districts/15/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk


###

PUT http://localhost:3000/districts/12/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


###

GET http://localhost:3000/states/12/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjczMDAwOTc3fQ.K4Lze_4AdPVoJQhfJ7AzQwmrZIOeNR-JkHehnmlwhPk











